    export const phrases = [
        { text: "1. La realización del Gran Despertar no es difícil, tan solo evita el apego y el rechazo.", link: "https://www.daizansoriano.com/1-la-via-suprema-no-es-dificil/" },
        { text: "2. Cuando no aparece el apego ni el rechazo, todo manifiesta su naturaleza luminosa.", link: "https://www.daizansoriano.com/2-cuando-no-hay-amor-ni-odio/" },
        { text: "3. Si aparece la más mínima diferencia, cielo y tierra quedan separados por un abismo.", link: "hhttps://www.daizansoriano.com/3-pero-si-se-crea-la-menor-diferencia/" },
        { text: "4. Si deseas ver la verdad ante ti, no tomes partido a favor ni en contra de nada.", link: "https://www.daizansoriano.com/4-para-que-se-declare-ante-los-ojos/" },
        { text: "5. El conflicto entre lo que aceptas y lo que rechazas, enferma el corazón y la mente.", link: "https://www.daizansoriano.com/5-la-lucha-entre-el-deseo-y-el-rechazo/" },
        { text: "6. Si no comprendes el principio profundo, te esfuerzas en bano en buscar la quietud.", link: "https://www.daizansoriano.com/6-al-no-comprender-el-sentido-profundo/" },
        { text: "7. Pleno como el gran vacío, nada falta, nada sobra.", link: "https://www.daizansoriano.com/07-perfecta-como-el-espacio-inmenso/" },
        { text: "8. Es precisamente por aferrarnos y rechazar, que perdemos nuestra armonía natural.", link: "https://www.daizansoriano.com/8-a-causa-del-apego-y-el-rechazo/" },
        { text: "9. No persigas lo que surge de los fenómenos, ni te aferres a la vacuidad.", link: "https://www.daizansoriano.com/9-no-hay-que-correr-detras-de-los-fenomenos/" },
        { text: "10. Cultiva una mente y un corazón ecuánimes, y la dualidad desaparecerá por sí misma.", link: "https://www.daizansoriano.com/10" },
        { text: "11. Intentar detener el movimiento solo lo intensifica aún más. cuando el movimiento cesa, la calma regresa.", link: "https://www.daizansoriano.com/11" },
        { text: "12. Aferrarse a los extremos, impide realizar la unidad.", link: "https://www.daizansoriano.com/12" },
        { text: "13. Si no alcanzas la unidad, te perderás en ambos extremos.", link: "https://www.daizansoriano.com/13" },
        { text: "14. Al rechazar la existencia, se pierde su verdadera naturaleza, al aferrarse al vacío, se niega su auténtico significado.", link: "https://www.daizansoriano.com/14" },
        { text: "15. Cuantas más palabras y pensamientos, más lejos estamos de nuestra armonía intrinseca.", link: "https://www.daizansoriano.com/15" },
        { text: "16. Cuando cesan las palabras y el sobrepensamiento, no hay lugar donde no haya claridad.", link: "https://www.daizansoriano.com/16" },
        { text: "17. Volver al origen es alcanzar la esencia, seguir las apariencias es alejarse de la realización.", link: "https://www.daizansoriano.com/17" },
        { text: "18. Cuando la luz se dirige hacia el interior, en un instante, se trasciende el vacío ilusorio.", link: "https://www.daizansoriano.com/18" },
        { text: "19. Los cambios que parecen tener lugar en el vacío, surgen de una percepción equivocada creada por la ignorancia.", link: "https://www.daizansoriano.com/19" },
        { text: "20. No necesitas buscar la verdad, tan solo suelta las percepciones erróneas.", link: "https://www.daizansoriano.com/20" },
        { text: "21. No te aferres a puntos de vista dualistas, actúa con cuidado y no los persigas.", link: "https://www.daizansoriano.com/21" },
        { text: "22. Apenas surge el juicio de correcto e incorrecto, mente y corazón se pierden en la confusión.", link: "https://www.daizansoriano.com/22" },
        { text: "23. Aunque la dualidad surge de la unidad, tampoco te aferres a la unidad.", link: "https://www.daizansoriano.com/23" },
        { text: "24. Cuando la mente no construye, los diez mil fenómenos están libres de error.", link: "https://www.daizansoriano.com/24" },
        { text: "25. Sin error, no hay fenómenos. Sin construcciones mentales, no hay apego ni rechazo.", link: "https://www.daizansoriano.com/25" },
        { text: "26. La ecuanimidad se puede desvanecer con las circustancias. Persiguiendo las circustancias nos perdemos en la confusión.", link: "https://www.daizansoriano.com/26" },
        { text: "27. El objeto depende del sujeto, el sujeto depende del objeto. Sujeto y objeto se originan mutuamente.", link: "https://www.daizansoriano.com/27" },
        { text: "28. Si se quiere comprender las dos partes, su origen es el mismo: vacío.", link: "https://www.daizansoriano.com/28" },
        { text: "29. Lo uno y el vacío son lo mismo, y ambos incluyen los diez mil fenómenos.", link: "https://www.daizansoriano.com/29" },
        { text: "30. Si no diferencias lo sutil de lo burdo, ¿Cómo podrías tomar partido hacia uno de los lados?", link: "https://www.daizansoriano.com/30" },
        { text: "31. El Dharma lo abarca todo, no es fácil ni difícil.", link: "https://www.daizansoriano.com/31" },
        { text: "32. La visión limitada, la duda y la desconfianza; Generan unas veces indecisión y otras apresuramiento.", link: "https://www.daizansoriano.com/32" },
        { text: "33. Si te aferras, pierdes la ecuanimidad, inevitablemente te desvías del camino.", link: "https://www.daizansoriano.com/33" },
        { text: "34. Si lo sueltas,vuelve a su propia naturaleza, su esencia no va ni viene.", link: "https://www.daizansoriano.com/34" },
        { text: "35. Cuando confiamos en la naturaleza de las cosas, hay armonía y se extinguen las aflicciones.", link: "https://www.daizansoriano.com/35" },
        { text: "36. Aferrarse a los pensamientos aleja de la realidad, la mente se oscurece y se hunde en lo indeseable.", link: "https://www.daizansoriano.com/36" },
        { text: "37. No es bueno agotar la energía vital, ¿Para qué huir, para qué seguir buscando?", link: "https://www.daizansoriano.com/37" },
        { text: "38. Si deseas alcanzar el Gran Despertar, no rechaces las seis sensaciones.", link: "https://www.daizansoriano.com/38" },
        { text: "39. Cuando no se rechazan las seis sensaciones, se alcanza el auténtico despertar.", link: "https://www.daizansoriano.com/39" },
        { text: "40. El sabio no actúa forzadamente, el ignorante se ata a sí mismo.", link: "https://www.daizansoriano.com/40" },
        { text: "41. El Dharma está más allá de la dualidad, pero los ilusos lo convierten en objeto de apego.", link: "https://www.daizansoriano.com/41" },
        { text: "42. Si tratas de usar la mente para comprender la mente, ¿Acaso no es un gran error?", link: "https://www.daizansoriano.com/42" },
        { text: "43. En la ignorancia surge la quietud y la agitación, en el despertar cesan el apego y el echazo.", link: "https://www.daizansoriano.com/43" },
        { text: "44. La existencia de los opuestos, es producto de la evaluación mental.", link: "https://www.daizansoriano.com/44" },
        { text: "45. Son solo sueños, ilusiones y reflejos vacíos, ¿por qué tratar de atraparlos?", link: "https://www.daizansoriano.com/45" },
        { text: "46. Ganar y perder, correcto e incorrecto…, suéltalos de una vez.", link: "https://www.daizansoriano.com/46" },
        { text: "47. Si los ojos no duermen, todos los sueños desaparecen por sí mismos.", link: "https://www.daizansoriano.com/47" },
        { text: "48. Cuando la mente no discrimina, los diez mil dharmas son uno.", link: "https://www.daizansoriano.com/48" },
        { text: "49. En la unidad, se realiza la esencia profunda, sin esfuerzo, los apegos se disuelven.", link: "https://www.daizansoriano.com/49" },
        { text: "50. Cuando todos los fenómenos son contemplados con ecuanimidad, retornan a su naturaleza original.", link: "https://www.daizansoriano.com/50" },
        { text: "51. Cuando desaparece cualquier estructura conceptual, la verdad última no puede ser atrapada con palabras.", link: "https://www.daizansoriano.com/51" },
        { text: "52. Cuando la quietud detiene el movimiento, no hay movimiento. Cuando el movimiento detiene la quietud, no hay quietud.", link: "https://www.daizansoriano.com/52" },
        { text: "53. Si la dualidad no existe, ¿cómo puede haber unidad?", link: "https://www.daizansoriano.com/53" },
        { text: "54. La realización última y absoluta, no sigue ninguna regla establecida.", link: "https://www.daizansoriano.com/54" },
        { text: "55. Cuando la mente alcanza la ecuanimidad, todo movimiento se aquieta.", link: "https://www.daizansoriano.com/55" },
        { text: "56. Cuando las dudas se disipan por completo, la confianza se vuelve serena y armoniosa.", link: "https://www.daizansoriano.com/56" },
        { text: "57. Todo se disuelve sin dejar rastro, no queda huella en la memoria.", link: "https://www.daizansoriano.com/57" },
        { text: "58. La vacuidad luminosa resplandece por sí misma, sin hacer ningún esfuerzo mental.", link: "https://www.daizansoriano.com/58" },
        { text: "59. Más allá del pensamiento, la mente y las emociones son insondables.", link: "https://www.daizansoriano.com/59" },
        { text: "60. La realidad tal cual es abarca todo, no hay otro, no hay yo.", link: "https://www.daizansoriano.com/60" },
        { text: "61. Para vivir instantáneamente en armonía con ello, basta decir: no dos.", link: "https://www.daizansoriano.com/61" },
        { text: "62. Todo es uno en la no-dualidad, no hay nada que no sea abarcado.", link: "https://www.daizansoriano.com/62" },
        { text: "63. Todos los sabios de las diez direcciones, viven de acuerdo a esta verdad ancestral.", link: "https://www.daizansoriano.com/63" },
        { text: "64. Esta verdad ancestral no está sujeta a lo breve o lo extenso, en ella un solo instante contiene la eternidad.", link: "https://www.daizansoriano.com/64" },
        { text: "65. Más allá del ser y del no ser, se manifiesta en todas partes.", link: "https://www.daizansoriano.com/65" },
        { text: "66. Lo infinitamente pequeño es idéntico a lo infinitamente grande, cuando se olvidan los límites y se disuelven las fronteras.", link: "https://www.daizansoriano.com/66" },
        { text: "67. Lo infinitamente grande es idéntico a lo infinitamente pequeño, los límites y las apariencias se desvanecen.", link: "https://www.daizansoriano.com/67" },
        { text: "68. El ser es, en sí mismo, no-ser, el no-ser es, en sí mismo, ser.", link: "https://www.daizansoriano.com/68" },
        { text: "69. Si no es así, entonces no hay necesidad de aferrarse.", link: "https://www.daizansoriano.com/69" },
        { text: "70. Uno es todo. Todo es uno.", link: "https://www.daizansoriano.com/70" },
        { text: "71. Si puedes ser así, no hay motivo para inquietarse por el resultado.", link: "https://www.daizansoriano.com/71" },
        { text: "72. La esencia de la confianza es la no-dualidad. La no-dualidad es la esencia de la confianza.", link: "https://www.daizansoriano.com/72" },
        { text: "73. Una vez aquí el lenguaje se silencia, y el pasado, el futuro y el presente desaparecen", link: "https://www.daizansoriano.com/73" }

];
