export const phrases = [
    export const phrases = [
        { text: "1. La Vía Suprema no es difícil. Evita sólo la atracción y el rechazo.", link: "https://www.daizansoriano.com/1-la-via-suprema-no-es-dificil/" },
        { text: "2. Cuando no hay amor ni odio, se manifiesta su naturaleza luminosa.", link: "https://www.daizansoriano.com/2-cuando-no-hay-amor-ni-odio/" },
        { text: "3. Pero si se crea la menor diferencia, un abismo separa la tierra del cielo.", link: "hhttps://www.daizansoriano.com/3-pero-si-se-crea-la-menor-diferencia/" },
        { text: "4. Para que se declare ante los ojos, no hay que situarse a favor ni en contra de nada.", link: "https://www.daizansoriano.com/4-para-que-se-declare-ante-los-ojos/" },
        { text: "5. La lucha entre el deseo y el rechazo enferma el corazón.", link: "https://www.daizansoriano.com/5-la-lucha-entre-el-deseo-y-el-rechazo/" },
        { text: "6. Al no comprender el sentido profundo, se perturba en vano la serenidad del espíritu.", link: "https://www.daizansoriano.com/6-al-no-comprender-el-sentido-profundo/" },
        { text: "7. Perfecta como el espacio inmenso, [a la Vía] nada le falta, nada le sobra.", link: "https://www.daizansoriano.com/07-perfecta-como-el-espacio-inmenso/" },
        { text: "8. A causa del apego y el rechazo, se pierde la armonía con la Vía.", link: "https://example.com/8" },
        { text: "9. No hay que correr detrás de los fenómenos, ni apegarse a la vacuidad.", link: "https://example.com/9" },
        { text: "10. Cuando el corazón mora sereno en la Unidad, la dualidad desaparece espontáneamente.", link: "https://example.com/10" },
        { text: "11. Cuando el movimiento cesa, regresa la calma, y de la calma surge de nuevo el movimiento.", link: "https://example.com/11" },
        { text: "12. Si hay apego a uno de los dos extremos, ¿cómo podrá ser realizada la Unidad?", link: "https://example.com/12" },
        { text: "13. Cuando no se conoce la Unidad, la función de ambos [extremos] se pierde.", link: "https://example.com/13" },
        { text: "14. Al rechazar el ser se pierde el ser, al apegarse a la vacuidad se niega la vacuidad.", link: "https://example.com/14" },
        { text: "15. Cuanto más se habla, cuanto más se piensa, más lejos se está de la Vía.", link: "https://example.com/15" },
        { text: "16. Si se deja de hablar y de pensar, no hay nada que no pueda ser comprendido.", link: "https://example.com/16" },
        { text: "17. Volver a la raíz es tocar la esencia, seguir las apariencias es alejarse del origen.", link: "https://example.com/17" },
        { text: "18. Cuando la luz es dirigida hacia el interior, la vacuidad queda inmediatamente trascendida.", link: "https://example.com/18" },
        { text: "19. Los cambios que parecen tener lugar en la vacuidad son percepciones ilusorias creadas por la ignorancia.", link: "https://example.com/19" },
        { text: "20. Es inútil querer alcanzar la verdad, basta con disolver la ignorancia.", link: "https://example.com/20" },
        { text: "21. No hay que apegarse a puntos de vista dualistas, hay que tener cuidado de no usarlos ni seguirlos.", link: "https://example.com/21" },
        { text: "22. A la mínima traza de correcto o erróneo, el corazón queda confundido.", link: "https://example.com/22" },
        { text: "23. Aunque la dualidad depende de la unidad, no hay que apegarse siquiera a la unidad.", link: "https://example.com/23" },
        { text: "24. Cuando la mente unificada no construye nada, los diez mil fenómenos son sin error.", link: "https://example.com/24" },
        { text: "25. Si no hay error, no hay fenómenos. Si no hay construcciones [mentales], no hay mente.", link: "https://example.com/25" },
        { text: "26. El sujeto se disuelve cuando desaparece el objeto. El objeto desaparece cuando se disuelve el sujeto.", link: "https://example.com/26" },
        { text: "27. El objeto es objeto en relación al sujeto. El sujeto es sujeto en relación al objeto.", link: "https://example.com/27" },
        { text: "28. Si se quiere conocer ambos aspectos, su origen es el mismo: vacuidad.", link: "https://example.com/28" },
        { text: "29. En la vacuidad ambos son idénticos y ambos incluyen todos los fenómenos.", link: "https://example.com/29" },
        { text: "30. Cuando no se diferencia lo sutil de lo grosero, la toma de partido se vuelve innecesaria.", link: "https://example.com/30" },
    "31. La Vía Suprema lo abarca todo, en ella no hay nada fácil ni nada difícil.",
    "32. Las ideas mezquinas generan dudas y desconfianzas; cuanto más rápido se va, más tarde se llega.",
    "33. Aferrarse [a la Vía] hace que se pierda el rumbo, e inevitablemente se llega a un callejón sin salida.",
    "34. Déjala fluir según su propia naturaleza, su esencia ni se mueve ni está quieta.",
    "35. La confianza en la naturaleza de las cosas es armonía con la Vía y gozo libre de preocupaciones.",
    "36. Pensar demasiado aleja de la realidad, la falta de claridad mental tampoco es beneficiosa.",
    "37. No es bueno agotar la energía vital, ¿de qué sirve huir de esto y buscar aquello?",
    "38. Aquellos que siguen el Gran Vehículo no rechazan los seis tipos de sensaciones.",
    "39. Cuando no se rechazan los seis tipos de sensaciones, se alcanza el perfecto despertar.",
    "40. El sabio no actúa. El necio se encadena a sí mismo.",
    "41. Un fenómeno no se diferencia de otro, es el apego el que crea la ilusión de la diferencia.",
    "42. Usar la mente para comprender la mente, ¿no es acaso un gran error?",
    "43. En la ignorancia se suceden orden y caos, en el despertar cesan la atracción y el rechazo.",
    "44. Todos los pares de opuestos son creados por el pensamiento.",
    "45. Los opuestos son como un sueño irreal, como un espejismo, ¿por qué agotarse intentando aferrarse a ellos?",
    "46. La ganancia y la pérdida, lo correcto y lo falso, en un instante se desvanecen para siempre.",
    "47. Si el ojo no duerme, todos los sueños se disuelven solos.",
    "48. Cuando la mente no discrimina, todas las existencias son unidad.",
    "49. Cuando se realiza la naturaleza profunda de esta unidad, la causalidad es instantáneamente trascendida.",
    "50. Cuando cada existencia es observada con ecuanimidad, ellas mismas retornan a su naturaleza original.",
    "51. Cuando se olvida la causalidad, las comparaciones se vuelven inútiles.",
    "52. Cuando el movimiento cesa, surge la inmovilidad. Cuando la inmovilidad se mueve, aparece el movimiento.",
    "53. Aunque ambos no pueden coexistir, ¿cómo podría darse lo uno sin lo otro?",
    "54. Aunque se investigue hasta el final del límite último, no se encontrarán reglas ni leyes.",
    "55. Cuando la mente se unifica consigo misma, toda actividad cesa.",
    "56. Cuando las dudas se agotan y se clarifican, la confianza se vuelve sincera, pura y armoniosa.",
    "57. No hay nada que no fluya, no hay nada que permanezca en la memoria.",
    "58. El vacío radiante se ilumina a sí mismo sin [que el ser humano tenga que] hacer ningún esfuerzo mental.",
    "59. El sabio mora en el no pensamiento, ya que ni el conocimiento ni los sentimientos humanos pueden sondear [esta verdad].",
    "60. En la realidad tal y como es, no hay ni yo ni otro.",
    "61. Para vivir instantáneamente en armonía [con ello], lo único que se puede decir es: no dos.",
    "62. En la no-dualidad todo es lo mismo, no hay nada que no esté incluido [en ella].",
    "63. Todos los sabios del mundo viven de acuerdo a esta verdad ancestral.",
    "64. Esta verdad ancestral no viene ni va, [en ella] un instante equivale a diez mil años.",
    "65. Ni existencia ni no existencia, por todas partes delante de los ojos.",
    "66. Lo infinitamente pequeño es idéntico a lo infinitamente grande, cuando se olvidan los límites y se disuelven las fronteras.",
    "67. Lo infinitamente grande es idéntico a lo infinitamente pequeño, nadie puede percibir la manifestación completa.",
    "68. Ser es no ser. No ser es ser.",
    "69. Siendo esto así, no hay nada a lo que aferrarse.",
    "70. Uno es todo. Todo es uno.",
    "71. Siendo esto siempre así, ¿por qué preocuparse por lo infinito?",
    "72. El corazón de la confianza es no-dos. No-dos es el corazón de la confianza.",
    "73. Una vez aquí las palabras cesan y el tiempo desaparece."
];
