    export const phrases = [
        { text: "1. La realización del Gran Despertar no es difícil, tan solo evita el apego y el rechazo.", link: "../xinxinming/../xinxinming/comentarios/comentarios1.html#01" },
        { text: "2. Cuando no aparece el apego ni el rechazo, todo manifiesta su naturaleza luminosa.", link: "../xinxinming/comentarios/comentarios1.html#02" },
        { text: "3. Si aparece la más mínima diferencia, cielo y tierra quedan separados por un abismo.", link: "../xinxinming/comentarios/comentarios1.html#03" },
        { text: "4. Si deseas ver la verdad ante ti, no tomes partido a favor ni en contra de nada.", link: "../xinxinming/comentarios/comentarios1.html#04" },
        { text: "5. El conflicto entre lo que aceptas y lo que rechazas, enferma el corazón y la mente.", link: "../xinxinming/comentarios/comentarios1.html#05" },
        { text: "6. Si no comprendes el principio profundo, te esfuerzas en bano en buscar la quietud.", link: "../xinxinming/comentarios/comentarios2.html#01" },
        { text: "7. Pleno como el gran vacío, nada falta, nada sobra.", link: "../xinxinming/comentarios/comentarios2.html#02" },
        { text: "8. Es precisamente por aferrarnos y rechazar, que perdemos nuestra armonía natural.", link: "../xinxinming/comentarios/comentarios2.html#03" },
        { text: "9. No persigas lo que surge de los fenómenos, ni te aferres a la vacuidad.", link: "../xinxinming/comentarios/comentarios2.html#04" },
        { text: "10. Cultiva una mente y un corazón ecuánimes, y la dualidad desaparecerá por sí misma.", link: "../xinxinming/comentarios/comentarios2.html#05" },
        { text: "11. Intentar detener el movimiento solo lo intensifica aún más. cuando el movimiento cesa, la calma regresa.", link: "../xinxinming/comentarios/comentarios3.html#01" },
        { text: "12. Aferrarse a los extremos, impide realizar la unidad.", link: "../xinxinming/comentarios/comentarios3.html#02" },
        { text: "13. Si no alcanzas la unidad, te perderás en ambos extremos.", link: "../xinxinming/comentarios/comentarios3.html#03" },
        { text: "14. Al rechazar la existencia, se pierde su verdadera naturaleza, al aferrarse al vacío, se niega su auténtico significado.", link: "../xinxinming/comentarios/comentarios3.html#04" },
        { text: "15. Cuantas más palabras y pensamientos, más lejos estamos de nuestra armonía intrínseca.", link: "../xinxinming/comentarios/comentarios3.html#05" },
        { text: "16. Cuando cesan las palabras y el sobrepensamiento, no hay lugar donde no haya claridad.", link: "../xinxinming/comentarios/comentarios4.html#01" },
        { text: "17. Volver al origen es alcanzar la esencia, seguir las apariencias es alejarse de la realización.", link: "../xinxinming/comentarios/comentarios4.html#02" },
        { text: "18. Cuando la luz se dirige hacia el interior, en un instante, se trasciende el vacío ilusorio.", link: "../xinxinming/comentarios/comentarios4.html#03" },
        { text: "19. Los cambios que parecen tener lugar en el vacío, surgen de una percepción equivocada creada por la ignorancia.", link: "../xinxinming/comentarios/comentarios4.html#04" },
        { text: "20. No necesitas buscar la verdad, tan solo suelta las percepciones erróneas.", link: "../xinxinming/comentarios/comentarios4.html#05" },
        { text: "21. No te aferres a puntos de vista dualistas, actúa con cuidado y no los persigas.", link: "../xinxinming/comentarios/comentarios5.html#01" },
        { text: "22. Apenas surge el juicio de correcto e incorrecto, mente y corazón se pierden en la confusión.", link: "../xinxinming/comentarios/comentarios5.html#02" },
        { text: "23. Aunque la dualidad surge de la unidad, tampoco te aferres a la unidad.", link: "../xinxinming/comentarios/comentarios5.html#03" },
        { text: "24. Cuando la mente no construye, los diez mil fenómenos están libres de error.", link: "../xinxinming/comentarios/comentarios5.html#04" },
        { text: "25. Sin error, no hay fenómenos. Sin construcciones mentales, no hay apego ni rechazo.", link: "../xinxinming/comentarios/comentarios5.html#05" },
        { text: "26. La ecuanimidad se puede desvanecer con las circunstancias. Persiguiendo las circunstancias nos perdemos en la confusión.", link: "../xinxinming/comentarios/comentarios6.html#01" },
        { text: "27. El objeto depende del sujeto, el sujeto depende del objeto. Sujeto y objeto se originan mutuamente.", link: "../xinxinming/comentarios/comentarios6.html#02" },
        { text: "28. Si se quiere comprender las dos partes, su origen es el mismo: vacío.", link: "../xinxinming/comentarios/comentarios6.html#03" },
        { text: "29. Lo uno y el vacío son lo mismo, y ambos incluyen los diez mil fenómenos.", link: "../xinxinming/comentarios/comentarios6.html#04" },
        { text: "30. Si no diferencias lo sutil de lo burdo, ¿Cómo podrías tomar partido hacia uno de los lados?", link: "../xinxinming/comentarios/comentarios6.html#05" },
        { text: "31. El Dharma lo abarca todo, no es fácil ni difícil.", link: "../xinxinming/comentarios/comentarios7.html#01" },
        { text: "32. La visión limitada, la duda y la desconfianza; Generan unas veces indecisión y otras apresuramiento.", link: "../xinxinming/comentarios/comentarios7.html#02" },
        { text: "33. Si te aferras, pierdes la ecuanimidad, inevitablemente te desvías del camino.", link: "../xinxinming/comentarios/comentarios7.html#03" },
        { text: "34. Si lo sueltas,vuelve a su propia naturaleza, su esencia no va ni viene.", link: "../xinxinming/comentarios/comentarios7.html#04" },
        { text: "35. Cuando confiamos en la naturaleza de las cosas, hay armonía y se extinguen las aflicciones.", link: "../xinxinming/comentarios/comentarios7.html#05" },
        { text: "36. Aferrarse a los pensamientos aleja de la realidad, la mente se oscurece y se hunde en lo indeseable.", link: "../xinxinming/comentarios/comentarios8.html#01" },
        { text: "37. No es bueno agotar la energía vital, ¿Para qué huir, para qué seguir buscando?", link: "../xinxinming/comentarios/comentarios8.html#02" },
        { text: "38. Si deseas alcanzar el Gran Despertar, no rechaces las seis sensaciones.", link: "../xinxinming/comentarios/comentarios8.html#03" },
        { text: "39. Cuando no se rechazan las seis sensaciones, se alcanza el auténtico despertar.", link: "../xinxinming/comentarios/comentarios8.html#04" },
        { text: "40. El sabio no actúa forzadamente, el ignorante se ata a sí mismo.", link: "../xinxinming/comentarios/comentarios8.html#05" },
        { text: "41. El Dharma está más allá de la dualidad, pero los ilusos lo convierten en objeto de apego.", link: "../xinxinming/comentarios/comentarios9.html#01" },
        { text: "42. Si tratas de usar la mente para comprender la mente, ¿Acaso no es un gran error?", link: "../xinxinming/comentarios/comentarios9.html#02" },
        { text: "43. En la ignorancia surge la quietud y la agitación, en el despertar cesan el apego y el echazo.", link: "../xinxinming/comentarios/comentarios9.html#03" },
        { text: "44. La existencia de los opuestos, es producto de la evaluación mental.", link: "../xinxinming/comentarios/comentarios9.html#04" },
        { text: "45. Son solo sueños, ilusiones y reflejos vacíos, ¿por qué tratar de atraparlos?", link: "../xinxinming/comentarios/comentarios9.html#05" },
        { text: "46. Ganar y perder, correcto e incorrecto…, suéltalos de una vez.", link: "../xinxinming/comentarios/comentarios10.html#01" },
        { text: "47. Si los ojos no duermen, todos los sueños desaparecen por sí mismos.", link: "../xinxinming/comentarios/comentarios10.html#02" },
        { text: "48. Cuando la mente no discrimina, los diez mil dharmas son uno.", link: "../xinxinming/comentarios/comentarios10.html#03" },
        { text: "49. En la unidad, se realiza la esencia profunda, sin esfuerzo, los apegos se disuelven.", link: "../xinxinming/comentarios/comentarios10.html#04" },
        { text: "50. Cuando todos los fenómenos son contemplados con ecuanimidad, retornan a su naturaleza original.", link: "../xinxinming/comentarios/comentarios10.html#05" },
        { text: "51. Cuando desaparece cualquier estructura conceptual, la verdad última no puede ser atrapada con palabras.", link: "../xinxinming/comentarios/comentarios11.html#01" },
        { text: "52. Cuando la quietud detiene el movimiento, no hay movimiento. Cuando el movimiento detiene la quietud, no hay quietud.", link: "../xinxinming/comentarios/comentarios11.html#02" },
        { text: "53. Si la dualidad no existe, ¿cómo puede haber unidad?", link: "../xinxinming/comentarios/comentarios11.html#03" },
        { text: "54. La realización última y absoluta, no sigue ninguna regla establecida.", link: "../xinxinming/comentarios/comentarios11.html#04" },
        { text: "55. Cuando la mente alcanza la ecuanimidad, todo movimiento se aquieta.", link: "../xinxinming/comentarios/comentarios11.html#05" },
        { text: "56. Cuando las dudas se disipan por completo, la confianza se vuelve serena y armoniosa.", link: "../xinxinming/comentarios/comentarios12.html#01" },
        { text: "57. Todo se disuelve sin dejar rastro, no queda huella en la memoria.", link: "../xinxinming/comentarios/comentarios12.html#02" },
        { text: "58. La vacuidad luminosa resplandece por sí misma, sin hacer ningún esfuerzo mental.", link: "../xinxinming/comentarios/comentarios12.html#03" },
        { text: "59. Más allá del pensamiento, la mente y las emociones son insondables.", link: "../xinxinming/comentarios/comentarios12.html#04" },
        { text: "60. La realidad tal cual es abarca todo, no hay otro, no hay yo.", link: "../xinxinming/comentarios/comentarios12.html#05" },
        { text: "61. Para vivir instantáneamente en armonía con ello, basta decir: no dos.", link: "../xinxinming/comentarios/comentarios13.html#01" },
        { text: "62. Todo es uno en la no-dualidad, no hay nada que no sea abarcado.", link: "../xinxinming/comentarios/comentarios13.html#02" },
        { text: "63. Todos los sabios de las diez direcciones, viven de acuerdo a esta verdad ancestral.", link: "../xinxinming/comentarios/comentarios13.html#03" },
        { text: "64. Esta verdad ancestral no está sujeta a lo breve o lo extenso, en ella un solo instante contiene la eternidad.", link: "../xinxinming/comentarios/comentarios13.html#04" },
        { text: "65. Más allá del ser y del no ser, se manifiesta en todas partes.", link: "../xinxinming/comentarios/comentarios13.html#05" },
        { text: "66. Lo infinitamente pequeño es idéntico a lo infinitamente grande, cuando se olvidan los límites y se disuelven las fronteras.", link: "../xinxinming/comentarios/comentarios14.html#01" },
        { text: "67. Lo infinitamente grande es idéntico a lo infinitamente pequeño, los límites y las apariencias se desvanecen.", link: "../xinxinming/comentarios/comentarios14.html#02" },
        { text: "68. El ser es, en sí mismo, no-ser, el no-ser es, en sí mismo, ser.", link: "../xinxinming/comentarios/comentarios14.html#03" },
        { text: "69. Si no es así, entonces no hay necesidad de aferrarse.", link: "../xinxinming/comentarios/comentarios14.html#04" },
        { text: "70. Uno es todo. Todo es uno.", link: "../xinxinming/comentarios/comentarios14.html#05" },
        { text: "71. Si puedes ser así, no hay motivo para inquietarse por el resultado.", link: "../xinxinming/comentarios/comentarios15.html#01" },
        { text: "72. La esencia de la confianza es la no-dualidad. La no-dualidad es la esencia de la confianza.", link: "../xinxinming/comentarios/comentarios15.html#02" },
        { text: "73. Una vez aquí el lenguaje se silencia, y el pasado, el futuro y el presente desaparecen", link: "../xinxinming/comentarios/comentarios15.html#03" }

];
